version: '3.4'

services:
  mylittleurlapp:
    image: mylittleurlapp
    build:
      context: .
      dockerfile: MyLittleUrlApp/Dockerfile

networks:
  default:
    external:
      name: mylittleurl-net 